SELECT
'--DELETE FROM dba.SPARAMETERVALUE; '
UNION
SELECT
'INSERT INTO dba.SPARAMETERVALUE
([SPARVAPPLICATIONELEMENTID], [SPARVID], [SPARVPARAMETERID], [SPARVSGRONAME],
[SPARVSUSEID], [SPARVVALUE]) VALUES ('
+        COALESCE(''''+[SPARVAPPLICATIONELEMENTID]+'''','NULL')
+','+ COALESCE(''''+[SPARVID]+'''','NULL')
+','+ COALESCE(''''+[SPARVPARAMETERID]+'''','NULL')
+','+ COALESCE(''''+[SPARVSGRONAME]+'''','NULL')
+','+ COALESCE(''''+[SPARVSUSEID]+'''','NULL')
+','+ COALESCE(''''+[SPARVVALUE] +'''','NULL')+');'
FROM [dba].[SPARAMETERVALUE];